services:
  - type: web
    name: lojasite-front
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: node server.js
    domains:
      - lojasite.com.br
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_URL
        value: https://lojasite-back.onrender.com
      - key: VITE_BASE_PATH
        value: /
