import './style.css';
import { icon } from './icons.js';

const API = (import.meta.env.VITE_API_URL || 'http://localhost:3000').replace(/\/$/, '');
const pathSegments = location.pathname.split('/').filter(Boolean);
const repositoryBase = String(import.meta.env.BASE_URL || '/').split('/').filter(Boolean)[0]?.toLowerCase();
const slug = (pathSegments[0]?.toLowerCase() === repositoryBase ? pathSegments[1] : pathSegments[0])?.toLowerCase() || '';
const state = { store: null, cart: JSON.parse(localStorage.getItem(`cart:${slug}`) || '{}'), token: sessionStorage.getItem(`token:${slug}`) || '', user: JSON.parse(sessionStorage.getItem(`user:${slug}`) || 'null'), category: 'Todos', query: '' };
const $ = selector => document.querySelector(selector);
const money = value => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);
const escapeHtml = value => { const el = document.createElement('span'); el.textContent = String(value ?? ''); return el.innerHTML; };

async function api(path, options = {}) {
  const response = await fetch(`${API}${path}`, { ...options, headers: { ...(state.token ? { authorization: `Bearer ${state.token}` } : {}), ...(options.body ? { 'content-type': 'application/json' } : {}), ...options.headers } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || 'Não foi possível concluir.');
  return data;
}
function saveCart() { localStorage.setItem(`cart:${slug}`, JSON.stringify(state.cart)); updateCartBadge(); }
function cartItems() { return state.store.products.filter(p => state.cart[p.id]).map(p => ({ ...p, quantity: state.cart[p.id] })); }
function total() { return cartItems().reduce((sum, item) => sum + item.price * item.quantity, 0); }
function toast(message, type='ok') { const el = document.createElement('div'); el.className = `toast ${type}`; el.textContent = message; $('#toast-root').append(el); setTimeout(() => el.remove(), 3200); }

function productCard(product) {
  return `<article class="product-card"><div class="product-art" style="--art:${product.color}"><span class="product-tag">${escapeHtml(product.category)}</span>${icon(product.icon, 92)}</div><div class="product-info"><h3>${escapeHtml(product.name)}</h3><p>${escapeHtml(product.description)}</p><div class="product-buy"><div>${product.oldPrice ? `<s>${money(product.oldPrice)}</s>` : ''}<strong>${money(product.price)}</strong></div><button class="add" data-add="${product.id}" aria-label="Adicionar ${escapeHtml(product.name)}">${icon('bag',20)}<span>Adicionar</span></button></div></div></article>`;
}
function renderProducts() {
  const products = state.store.products.filter(p => (state.category === 'Todos' || p.category === state.category) && `${p.name} ${p.description}`.toLowerCase().includes(state.query.toLowerCase()));
  $('#products').innerHTML = products.length ? products.map(productCard).join('') : '<div class="empty"><h3>Nenhum produto encontrado</h3><p>Tente outro termo ou categoria.</p></div>';
  document.querySelectorAll('[data-add]').forEach(btn => btn.onclick = () => { state.cart[btn.dataset.add] = (state.cart[btn.dataset.add] || 0) + 1; saveCart(); toast('Produto adicionado ao carrinho.'); btn.classList.add('added'); setTimeout(() => btn.classList.remove('added'), 500); });
}
function updateCartBadge() { const count = Object.values(state.cart).reduce((a,b) => a+b, 0); const el = $('#cart-count'); if (el) { el.textContent = count; el.hidden = count === 0; } }
function renderApp() {
  const store = state.store; document.title = `${store.name} · Loja online`; document.documentElement.style.setProperty('--primary', store.theme.primary); document.documentElement.style.setProperty('--accent', store.theme.accent);
  const categories = ['Todos', ...new Set(store.products.map(p => p.category))];
  $('#app').innerHTML = `<header class="header store-header"><a class="logo store-logo" href="${import.meta.env.BASE_URL}${slug}" aria-label="${escapeHtml(store.name)}"><span class="logo-fallback">${store.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><img id="store-logo-image" src="${import.meta.env.BASE_URL}imagens/${store.id}/logo.png" alt="Logo ${escapeHtml(store.name)}"><strong>${escapeHtml(store.name)}</strong></a><label class="header-search">⌕<input id="header-search" placeholder="Pesquisar produtos" aria-label="Pesquisar produtos"></label><div class="header-actions">${state.user ? `<button class="user-button" id="account">Olá, ${escapeHtml(state.user.name.split(' ')[0])}</button>` : `<button class="login-button" id="login">Entrar</button>`}<button class="cart-button" id="cart" aria-label="Abrir carrinho">${icon('bag',22)}<span>Carrinho</span><b id="cart-count" hidden>0</b></button></div></header>
  <main><section class="hero"><div class="hero-copy"><span class="kicker">NOVIDADES DA SEMANA</span><h1>${escapeHtml(store.tagline)}</h1><p>Escolhas especiais, compra segura e entrega para todo o Brasil.</p><a href="#produtos">Ver produtos <span>↗</span></a></div><div class="hero-visual"><div class="orb one"></div><div class="orb two"></div><div class="hero-card back">${icon(store.products[1].icon,94)}</div><div class="hero-card front">${icon(store.products[0].icon,120)}<small>A partir de</small><strong>${money(store.products[0].price)}</strong></div></div></section>
  <section class="benefits"><div><b>↗</b><span><strong>Envio rápido</strong><small>Para todo o Brasil</small></span></div><div><b>◇</b><span><strong>Compra protegida</strong><small>Pagamento seguro</small></span></div><div><b>↺</b><span><strong>Troca fácil</strong><small>Até 7 dias</small></span></div><div><b>♡</b><span><strong>Atendimento</strong><small>Feito por pessoas</small></span></div></section>
  <section class="catalog" id="produtos"><div class="section-head"><div><span class="kicker">NOSSA SELEÇÃO</span><h2>Produtos em destaque</h2></div></div><div class="filters">${categories.map((c,i)=>`<button data-category="${escapeHtml(c)}" class="${i===0?'active':''}">${escapeHtml(c)}</button>`).join('')}</div><div class="product-grid" id="products"></div></section>
  <section class="about" id="sobre"><span class="kicker">COMPRE COM CONFIANÇA</span><h2>Uma experiência simples do começo ao fim.</h2><p>Produtos escolhidos com cuidado, pagamento dentro da loja e acompanhamento dos seus pedidos em um só lugar.</p></section></main>
  <footer><div class="logo inverse"><span>${store.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><strong>${escapeHtml(store.name)}</strong></div><p>© ${new Date().getFullYear()} ${escapeHtml(store.name)}. Todos os direitos reservados.</p>${developerFooter()}</footer>`;
  updateCartBadge(); renderProducts();
  const logoImage = $('#store-logo-image'); logoImage.onerror = () => { if (!logoImage.dataset.jpgTried) { logoImage.dataset.jpgTried = 'true'; logoImage.src = `${import.meta.env.BASE_URL}imagens/${store.id}/logo.jpg`; return; } logoImage.hidden = true; $('.logo-fallback').hidden = false; }; logoImage.onload = () => { $('.logo-fallback').hidden = true; };
  $('#login')?.addEventListener('click', openLogin); $('#account')?.addEventListener('click', openAccount); $('#cart').onclick = openCart; $('#header-search').oninput = e => { state.query = e.target.value; renderProducts(); };
  document.querySelectorAll('[data-category]').forEach(btn => btn.onclick = () => { state.category = btn.dataset.category; document.querySelectorAll('[data-category]').forEach(x => x.classList.toggle('active', x===btn)); renderProducts(); });
}
function modal(content, className='') { $('#modal-root').innerHTML = `<div class="modal-overlay"><section class="modal ${className}" role="dialog" aria-modal="true"><button class="close" aria-label="Fechar">×</button>${content}</section></div>`; $('.close').onclick = closeModal; $('.modal-overlay').onclick = e => { if (e.target.classList.contains('modal-overlay')) closeModal(); }; }
function closeModal() { $('#modal-root').innerHTML = ''; }

function developerFooter() {
  return `<a class="developer-credit" href="mailto:thiago07cb2@gmail.com" aria-label="Contato com o desenvolvedor"><img src="${import.meta.env.BASE_URL}imagens/logo_dev.png" alt="Logo do desenvolvedor"><span><small>DESENVOLVIDO POR</small><strong>Thiago Carvalho · EVOTECHUB</strong><em>thiago07cb2@gmail.com</em></span></a>`;
}

function renderPortal() {
  document.title = 'LojaSite · Lojas online para organizações';
  document.documentElement.style.setProperty('--primary', '#176bff');
  document.documentElement.style.setProperty('--accent', '#70e1c0');
  $('#app').innerHTML = `<div class="portal"><header class="header portal-header"><a class="logo portal-logo" href="${import.meta.env.BASE_URL}"><img src="${import.meta.env.BASE_URL}imagens/logo.png" alt="Logo LojaSite"><strong>LojaSite</strong></a><nav><a href="#como-funciona">Como funciona</a><a href="#manual">Manual</a><a href="#contato">Contato</a></nav><a class="portal-access" href="#acessar">Acessar uma loja</a></header>
  <main><section class="portal-hero"><div><span class="kicker">COMÉRCIO DIGITAL MULTIORGANIZAÇÃO</span><h1>Uma loja exclusiva para cada negócio.</h1><p>O LojaSite reúne catálogo, clientes, pedidos e pagamentos em uma experiência segura. Cada organização possui seu próprio endereço e sua identidade.</p><a class="portal-primary" href="#como-funciona">Conhecer o sistema <span>↓</span></a></div><div class="portal-window"><div class="window-bar"><i></i><i></i><i></i><small>lojasite.com.br/sua-loja</small></div><div class="window-content"><span>LS</span><div><small>SEU ENDEREÇO EXCLUSIVO</small><strong>lojasite.com.br/<b>sua-organizacao</b></strong></div></div></div></section>
  <section class="portal-section" id="como-funciona"><div class="portal-title"><span class="kicker">COMO FUNCIONA</span><h2>O link identifica a organização.</h2><p>Não é necessário informar empresa ou organização no login. O LojaSite reconhece automaticamente a loja pelo endereço acessado.</p></div><div class="steps"><article><b>01</b><h3>Acesse o link</h3><p>Use o endereço exclusivo fornecido pela sua organização.</p></article><article><b>02</b><h3>Explore os produtos</h3><p>O catálogo completo aparece na página inicial, mesmo antes do login.</p></article><article><b>03</b><h3>Entre e compre</h3><p>Abra o modal de login, finalize o pedido e pague dentro da loja.</p></article></div></section>
  <section class="portal-section portal-manual" id="manual"><div class="portal-title"><span class="kicker">MANUAL RÁPIDO</span><h2>Comece em poucos passos.</h2></div><div class="manual-grid"><div><h3>Para clientes</h3><ol><li>Acesse o link fornecido pela organização.</li><li>Escolha os produtos e abra o carrinho.</li><li>Entre com seu login e senha.</li><li>Informe os dados e selecione PIX ou cartão.</li><li>Acompanhe o pedido em “Minha conta”.</li></ol></div><div><h3>Endereço personalizado</h3><p>O sufixo é escolhido em comum acordo com cada organização. Por exemplo, “Lojão da Noruega” poderia usar:</p><div class="link-example">lojasite.com.br/<strong>lojao_da_noruega</strong></div><p>Use sempre o endereço oficial recebido. Por privacidade, o portal não divulga a relação de organizações atendidas.</p></div></div></section>
  <section class="portal-contact" id="contato"><div><span class="kicker">SUPORTE E DESENVOLVIMENTO</span><h2>Precisa de ajuda?</h2><p>Entre em contato para suporte, implantação de uma organização ou informações sobre o sistema.</p></div><a href="mailto:thiago07cb2@gmail.com">thiago07cb2@gmail.com <span>↗</span></a></section>
  <section class="portal-access-section" id="acessar"><span class="kicker">ACESSO À SUA LOJA</span><h2>Informe o sufixo do seu link</h2><form id="portal-access-form"><span>lojasite.com.br/</span><input name="suffix" placeholder="sua_organizacao" pattern="[a-zA-Z0-9_-]+" required><button type="submit">Acessar</button></form><p>O sufixo é fornecido pela sua organização.</p></section></main>
  <footer><div class="logo inverse portal-logo"><img src="${import.meta.env.BASE_URL}imagens/logo.png" alt="Logo LojaSite"><strong>LojaSite</strong></div><p>© ${new Date().getFullYear()} EVOTECHUB. Todos os direitos reservados.</p>${developerFooter()}</footer></div>`;
  $('#portal-access-form').onsubmit = event => { event.preventDefault(); const suffix = new FormData(event.currentTarget).get('suffix').trim().toLowerCase(); location.href = `${import.meta.env.BASE_URL}${encodeURIComponent(suffix)}`; };
}
function openLogin(next) {
  modal(`<div class="modal-mark">${state.store.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><span class="kicker">ÁREA DO CLIENTE</span><h2>Bom ter você aqui</h2><p class="muted">Entre para finalizar sua compra e acompanhar pedidos.</p><form id="login-form"><label>Login<input name="login" autocomplete="username" placeholder="Seu login" required></label><label>Senha<input name="password" type="password" autocomplete="current-password" placeholder="Sua senha" minlength="6" required></label><button class="primary" type="submit">Entrar</button><p class="form-error" aria-live="polite"></p></form>`, 'login-modal');
  $('#login-form').onsubmit = async e => { e.preventDefault(); const btn=e.target.querySelector('button'); btn.disabled=true; btn.textContent='Entrando...'; try { const body=Object.fromEntries(new FormData(e.target)); const data=await api(`/api/stores/${slug}/auth/login`,{method:'POST',body:JSON.stringify(body)}); state.token=data.token; state.user=data.user; sessionStorage.setItem(`token:${slug}`,data.token); sessionStorage.setItem(`user:${slug}`,JSON.stringify(data.user)); closeModal(); renderApp(); toast('Login realizado com sucesso.'); if(next) next(); } catch(error){ $('.form-error').textContent=error.message; btn.disabled=false; btn.textContent='Entrar'; } };
}
function openAccount() { modal(`<span class="kicker">MINHA CONTA</span><h2>${escapeHtml(state.user.name)}</h2><p class="muted">${escapeHtml(state.user.email)}</p><button class="secondary full" id="orders">Ver meus pedidos</button><button class="text-button full" id="logout">Sair da conta</button>`); $('#orders').onclick=showOrders; $('#logout').onclick=()=>{ sessionStorage.removeItem(`token:${slug}`);sessionStorage.removeItem(`user:${slug}`);state.token='';state.user=null;closeModal();renderApp();toast('Você saiu da conta.');}; }
function openCart() {
  const items=cartItems(); modal(`<span class="kicker">SEU CARRINHO</span><h2>${items.length ? `${items.length} ${items.length===1?'produto':'produtos'}` : 'Carrinho vazio'}</h2><div class="cart-list">${items.map(i=>`<div class="cart-item"><div class="cart-thumb" style="--art:${i.color}">${icon(i.icon,38)}</div><div><strong>${escapeHtml(i.name)}</strong><small>${money(i.price)}</small><div class="qty"><button data-minus="${i.id}">−</button><span>${i.quantity}</span><button data-plus="${i.id}">+</button></div></div><button class="remove" data-remove="${i.id}" aria-label="Remover">×</button></div>`).join('') || '<p class="muted">Adicione produtos para começar.</p>'}</div>${items.length?`<div class="cart-total"><span>Total</span><strong>${money(total())}</strong></div><button class="primary full" id="checkout">Continuar para pagamento</button>`:''}`, 'cart-modal');
  document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{ if(--state.cart[b.dataset.minus]<=0)delete state.cart[b.dataset.minus];saveCart();openCart();}); document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{state.cart[b.dataset.plus]++;saveCart();openCart();}); document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{delete state.cart[b.dataset.remove];saveCart();openCart();}); $('#checkout')?.addEventListener('click',()=> state.user ? openCheckout() : openLogin(openCheckout));
}
function openCheckout() {
  modal(`<span class="kicker">CHECKOUT SEGURO</span><h2>Finalizar pedido</h2><form id="checkout-form"><div class="checkout-grid"><label>Nome completo<input name="name" value="${escapeHtml(state.user.name)}" required></label><label>CPF ou CNPJ<input name="cpfCnpj" inputmode="numeric" placeholder="000.000.000-00" required></label><label>Celular<input name="phone" type="tel" placeholder="(00) 00000-0000" required></label></div><h3>Forma de pagamento</h3><div class="pay-options"><label><input type="radio" name="method" value="pix" checked><span><b>PIX</b><small>Aprovação rápida</small></span></label><label><input type="radio" name="method" value="card"><span><b>Cartão</b><small>Crédito à vista</small></span></label></div><div id="card-fields" class="card-fields" hidden><label>Nome no cartão<input name="holderName"></label><label>Número do cartão<input name="number" inputmode="numeric"></label><label>Validade<input name="expiry" placeholder="MM/AAAA"></label><label>CVV<input name="ccv" inputmode="numeric"></label><label>CEP<input name="postalCode" inputmode="numeric"></label><label>Número do endereço<input name="addressNumber"></label></div><div class="cart-total"><span>Total</span><strong>${money(total())}</strong></div><button class="primary full" type="submit">Pagar ${money(total())}</button><p class="form-error"></p></form>`, 'checkout-modal');
  document.querySelectorAll('[name=method]').forEach(r=>r.onchange=()=>{$('#card-fields').hidden=r.value!=='card';});
  $('#checkout-form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Processando com segurança...';const f=Object.fromEntries(new FormData(e.target));const [expiryMonth,expiryYear]=String(f.expiry||'').split('/');try{const data=await api(`/api/stores/${slug}/orders`,{method:'POST',body:JSON.stringify({items:cartItems().map(i=>({productId:i.id,quantity:i.quantity})),method:f.method,customer:{name:f.name,cpfCnpj:f.cpfCnpj,phone:f.phone},card:{holderName:f.holderName,number:f.number,expiryMonth,expiryYear,ccv:f.ccv,postalCode:f.postalCode,addressNumber:f.addressNumber}})});state.cart={};saveCart();showPayment(data.order);}catch(error){$('.form-error').textContent=error.message;btn.disabled=false;btn.textContent=`Pagar ${money(total())}`;}};
}
function showPayment(order) { const p=order.payment; modal(`<div class="success-icon">${p.status==='CONFIRMED'?'✓':'◇'}</div><span class="kicker">PEDIDO ${escapeHtml(order.id)}</span><h2>${p.status==='CONFIRMED'?'Pagamento aprovado!':'Agora é só pagar o PIX'}</h2>${p.method==='pix'?`<p class="muted">Copie o código abaixo e pague no aplicativo do seu banco.</p>${p.pix?.encodedImage?`<img class="qr" src="data:image/png;base64,${p.pix.encodedImage}" alt="QR Code PIX">`:''}<div class="pix-code">${escapeHtml(p.pix?.payload||'')}</div><button class="primary full" id="copy-pix">Copiar código PIX</button>`:`<p class="muted">Seu pedido foi confirmado e já está sendo preparado.</p>`}<button class="text-button full" id="finish">Voltar para a loja</button>`, 'result-modal'); $('#copy-pix')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(p.pix.payload);toast('Código PIX copiado.');});$('#finish').onclick=closeModal; }
async function showOrders(){try{const data=await api(`/api/stores/${slug}/orders`);modal(`<span class="kicker">MINHA CONTA</span><h2>Meus pedidos</h2><div class="orders">${data.orders.map(o=>`<article><div><strong>${escapeHtml(o.id)}</strong><small>${new Date(o.createdAt).toLocaleDateString('pt-BR')}</small></div><span class="status">${escapeHtml(o.status.replaceAll('_',' '))}</span><b>${money(o.total)}</b></article>`).join('')||'<p class="muted">Você ainda não fez pedidos.</p>'}</div>`);}catch(e){toast(e.message,'error');}}

async function init(){if(!slug)return renderPortal();try{const data=await api(`/api/stores/${slug}`);state.store=data.store;renderApp();if(state.token){try{const session=await api(`/api/stores/${slug}/session`);state.user=session.user;}catch{state.token='';state.user=null;sessionStorage.removeItem(`token:${slug}`);sessionStorage.removeItem(`user:${slug}`);}renderApp();}}catch(error){$('#app').innerHTML=`<main class="not-found"><div><span>404</span><h1>Loja não encontrada</h1><p>Confira o endereço informado. Cada organização possui seu próprio link.</p><a href="${import.meta.env.BASE_URL}">Ir para o portal LojaSite</a></div></main>`;}}
init();
